// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "79542e0f-41a6-4ed5-8bfb-a88ec645aa5f");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1674253979);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1674253914);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1674254009);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{fa932f0a-877d-414a-9c8e-e1351b7c6166}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.home-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1674253912);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fde6f8ed-bc74-428e-aace-18262f789e7a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1674253923086");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1674255725086");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1674253914890");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1674275514890");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221205141915");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "https://explore.network.brand.blockfabric.net");
user_pref("browser.startup.homepage_override.buildID", "20221205141915");
user_pref("browser.startup.homepage_override.mstone", "102.6.0");
user_pref("browser.startup.lastColdStartupCheck", 1675028544);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "102.6.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "cd5dfe3a955c4c00aa9cb6ff437c5b28");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221205141915");
user_pref("extensions.lastAppVersion", "102.6.0");
user_pref("extensions.lastPlatformVersion", "102.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"a7ab7e9c-6f09-4725-8f64-6dd369ce55a3\",\"formautofill@mozilla.org\":\"e945a283-f7e5-43bb-9c15-f70929c4097b\",\"pictureinpicture@mozilla.org\":\"28981712-b693-4e50-90b1-a718b69bcd15\",\"screenshots@mozilla.org\":\"67097664-db81-4266-b7e1-038728f441ed\",\"webcompat-reporter@mozilla.org\":\"4bacb505-1aaa-455d-850f-5b1b854fce4c\",\"webcompat@mozilla.org\":\"9d968b92-ff89-4df3-a821-f52b4c2f11f8\",\"default-theme@mozilla.org\":\"dee55999-2492-4b87-bfc2-b51ae2f3b043\",\"addons-search-detection@mozilla.com\":\"7c65676f-044d-4f67-907f-21db43602ce8\",\"google@search.mozilla.org\":\"f97a7729-165d-4901-adfd-c72873c74b4b\",\"amazondotcom@search.mozilla.org\":\"5a35a866-a962-4d19-891b-a08492e78e33\",\"wikipedia@search.mozilla.org\":\"caa2370b-242a-4ace-9769-07d28b4ee650\",\"bing@search.mozilla.org\":\"3e669a62-76d3-4719-a218-e695947fec0f\",\"ddg@search.mozilla.org\":\"240cda7e-3655-424b-83c2-650e11ef01e1\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1674253913);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a5907a48-61a6-4830-bd4b-fa041560f4ca");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1675028543);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20221205141915");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
